language: python
python:
  - 2.6
  - 2.7
  - 3.3
install:
  - pip install -r requirements.txt
script:
  - coverage run --source=coveralls setup.py test
  - coverage report -m
  - python setup.py develop
  - bin/coveralls

