version: 2.1

orbs:
  linter: thekevjames/linter@1

jobs:
  toxpy:
    docker:
      - image: python:<<parameters.docker_image>>-alpine
    parameters:
      docker_image:
        type: string
      # TODO: figure out `<<parameters.docker_image>>.replace('.','')`
      tox_environment:
        type: string
    steps:
      - run: apk add --no-cache gcc git libffi-dev musl-dev openssh-client openssl-dev
      - checkout
      - run: pip install tox tox-factor
      - run: tox -f <<parameters.tox_environment>>
      - run: tox -e coveralls

  toxpypy:
    docker:
      - image: pypy:<<parameters.docker_image>>-slim
    parameters:
      docker_image:
        type: string
      # TODO: figure out `<<parameters.docker_image>>.replace('.','')`
      tox_environment:
        type: string
    steps:
      - checkout
      - run: pip install tox tox-factor
      - run: tox -f <<parameters.tox_environment>>
      - run: tox -e coveralls

workflows:
  run-jobs:
    jobs:
      - linter/pre-commit:
          python_version: 3.7.5

      - toxpy:
          name: test-py2.7
          docker_image: '2.7'
          tox_environment: py27
      - toxpy:
          name: test-py3.4
          docker_image: '3.4'
          tox_environment: py34
      - toxpy:
          name: test-py3.5
          docker_image: '3.5'
          tox_environment: py35
      - toxpy:
          name: test-py3.6
          docker_image: '3.6'
          tox_environment: py36
      - toxpy:
          name: test-py3.7
          docker_image: '3.7'
          tox_environment: py37
      - toxpy:
          name: test-py3.8
          docker_image: '3.8'
          tox_environment: py38

      - toxpypy:
          name: test-pypy2-5
          docker_image: 2-5
          tox_environment: pypy
      - toxpypy:
          name: test-pypy2-6
          docker_image: 2-6
          tox_environment: pypy
      - toxpypy:
          name: test-pypy2-7
          docker_image: 2-7
          tox_environment: pypy

      - toxpypy:
          name: test-pypy3-5
          docker_image: 3-5
          tox_environment: pypy3
      - toxpypy:
          name: test-pypy3-6
          docker_image: 3-6
          tox_environment: pypy3
      - toxpypy:
          name: test-pypy3-7
          docker_image: 3-7
          tox_environment: pypy3
