version: 2.1

orbs:
  linter: thekevjames/linter@1

jobs:
  toxpy:
    docker:
      - image: python:<<parameters.docker_image>>-alpine
    parameters:
      docker_image:
        type: string
      # TODO: figure out `<<parameters.docker_image>>.replace('.','')`
      tox_environment:
        type: string
    steps:
      - run: apk add --no-cache gcc git libffi-dev musl-dev openssh-client openssl-dev
      - checkout
      - run: pip install tox tox-factor
      - run: tox -f <<parameters.tox_environment>>

  toxpypy:
    docker:
      - image: pypy:<<parameters.docker_image>>
    parameters:
      docker_image:
        type: string
      # TODO: figure out `<<parameters.docker_image>>.replace('.','')`
      tox_environment:
        type: string
    steps:
      - checkout
      - run: pip install tox tox-factor
      - run: tox -f <<parameters.tox_environment>>

workflows:
  run-jobs:
    jobs:
      - linter/pre-commit:
          python_version: 3.7.5

      - toxpy:
          docker_image: '2.7'
          tox_environment: py27
      - toxpy:
          docker_image: '3.4'
          tox_environment: py34
      - toxpy:
          docker_image: '3.5'
          tox_environment: py35
      - toxpy:
          docker_image: '3.6'
          tox_environment: py36
      - toxpy:
          docker_image: '3.7'
          tox_environment: py37

      - toxpypy:
          docker_image: 2-5.8.0
          tox_environment: pypy
      - toxpypy:
          docker_image: 2-6.0.0
          tox_environment: pypy
      - toxpypy:
          docker_image: 3-5.8.0
          tox_environment: pypy3
      - toxpypy:
          docker_image: 3-6.0.0
          tox_environment: pypy3
